### ISSUE TITLE
Can the Exercise Price of Warrants and Options be Added to Plans Ledgers, the Non-Plan Options Ledger, and the Warrants Ledger?

### ISSUE THREAD

**Issue by aporretta4** [Open-Cap-Table-Coalition/ocx#60]
### What can we help you with?

As of now, there is no way for one to figure out the exercise price of Warrants and Options in any of the ledgers that list those securities. Can this feature be added?

**Comment by stephen-npm** [comment]
Sounds like "Price Per Share" is the general term across all Ledgers whether it's for a stock class, a plan, a non-plan, etc and it's representing the associating value for what contextually it needs to be based off the asset type:
- "Price Per Share" for stock class -> cost basis
- "Price Per Share" for option -> exercise price
- "Price Per Share" for warrant -> exercise price

It would be nice to add this decision to documentation somewhere however, because it's not obvious to me either as is

**Comment by aporretta4** [comment]
Thanks @stephen-npm. Given that:

> "Price Per Share" for option -> exercise price
"Price Per Share" for warrant -> exercise price

I'll close this issue.
